# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a820cac24a7305a7e897e6034e6f723a1d5c78647dfda4701232f3ec5bcb4991fae6377ffdcdd39dfcc2e1d74331496805c5cfb7acacc70d800ccb89250dcf24

test:
  secret_key_base: b7c7406bf6fb5c24dc188b1c826616b1dded2a0749a8d6d84f7fb18b30a97359df5d3ffbc6d12035d14bb647cd75da80d4092cc057a080209b7a8db6c880cea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
